#! /usr/bin/env python

# Test program as shown in Beginning Python - From Novice
# to Professional, on page 21

name = input("What is your name? ") # raw_input does not exist in python3
print("Hello, " + name + "!")